### ISSUE TITLE
Issue with bootloader

### ISSUE THREAD

**Issue by PointyyP** [adamb314/ServoProject#15]
After performing:

cd filename
sudo openocd

// I get "command not found"

![IMG20231023180807](https://github.com/adamb314/ServoProject/assets/146996873/05043109-a119-40d4-a137-7f11a5c21913)

**Comment by smith901** [comment]
Looks like `openocd` isn't installed. Follow instructions [from this file in the project](https://github.com/adamb314/ServoProject/blob/main/PcbDesignes/ServoBrushed/burnBootloaderWithOpenOCD.txt).

**Comment by PointyyP** [comment]
I was following the instructions and thought I installed openocd, but I'll give it a try again. Thanks!

**Comment by PointyyP** [comment]
After installing openocd and soldering the three pins (D,C,Reset) I have a new error message after executing sudo openocd

![16981838757163686557048770613829](https://github.com/adamb314/ServoProject/assets/146996873/f660e6af-efe5-4b8d-9c8b-58c949d36f38)

**Comment by adamb314** [comment]
First of all check so that you have connected the right pins on the pi:

![20231025_092226.jpg](https://github.com/adamb314/ServoProject/assets/82474186/a68e73c3-5ab8-4dcc-b8c1-ae32fa1fc3ec)

Orange is clock, brown data and red is reset.

Second, try powering the PCB via the raspberry pi with a short cable (to get a stable ground).

If you still have problems, it might help lowering the frequency. Add this line:

Adapter speed 80

Directly under the line:
source [find interface/raspberrypi2-native.cfg]

In the openOCD script.

Hope you get it to work.
